export const data = [
  {
    name: "John Doe",
    age: 28,
    email: "john.doe@example.com",
    address: "123 Main St, Cityville",
    phone: "555-1234",
    gender: "Male",
  },
  {
    name: "Alice Smith",
    age: 35,
    email: "alice.smith@example.com",
    address: "456 Oak St, Townsville",
    phone: "555-5678",
    gender: "Female",
  },
  {
    name: "Bob Johnson",
    age: 22,
    email: "bob.johnson@example.com",
    address: "789 Pine St, Villagetown",
    phone: "555-8765",
    gender: "Male",
  },
  {
    name: "Eva Miller",
    age: 29,
    email: "eva.miller@example.com",
    address: "321 Cedar St, Hamletsville",
    phone: "555-4321",
    gender: "Female",
  },
  {
    name: "David Brown",
    age: 31,
    email: "david.brown@example.com",
    address: "654 Birch St, Countryside",
    phone: "555-9876",
    gender: "Male",
  },
  {
    name: "Sophia Davis",
    age: 25,
    email: "sophia.davis@example.com",
    address: "987 Elm St, Suburbia",
    phone: "555-2345",
    gender: "Female",
  },
  {
    name: "Ryan Wilson",
    age: 32,
    email: "ryan.wilson@example.com",
    address: "101 Maple St, Outskirts",
    phone: "555-6789",
    gender: "Male",
  },
  {
    name: "Olivia Lee",
    age: 27,
    email: "olivia.lee@example.com",
    address: "202 Walnut St, Uptown",
    phone: "555-3456",
    gender: "Female",
  },
  {
    name: "Michael Anderson",
    age: 30,
    email: "michael.anderson@example.com",
    address: "303 Spruce St, Downtown",
    phone: "555-8765",
    gender: "Male",
  },
  {
    name: "Emma Taylor",
    age: 26,
    email: "emma.taylor@example.com",
    address: "404 Pine St, Riverside",
    phone: "555-4321",
    gender: "Female",
  },
  {
    name: "Daniel White",
    age: 33,
    email: "daniel.white@example.com",
    address: "505 Cedar St, Lakeside",
    phone: "555-7890",
    gender: "Male",
  },
  {
    name: "Grace Hall",
    age: 24,
    email: "grace.hall@example.com",
    address: "606 Oak St, Mountainside",
    phone: "555-1234",
    gender: "Female",
  },
  {
    name: "William Clark",
    age: 28,
    email: "william.clark@example.com",
    address: "707 Elm St, Seaside",
    phone: "555-5678",
    gender: "Male",
  },
  {
    name: "Ava Allen",
    age: 34,
    email: "ava.allen@example.com",
    address: "808 Birch St, Hillside",
    phone: "555-2345",
    gender: "Female",
  },
  {
    name: "Christopher Carter",
    age: 29,
    email: "christopher.carter@example.com",
    address: "909 Maple St, Countryside",
    phone: "555-8765",
    gender: "Male",
  },
  {
    name: "Emily Moore",
    age: 31,
    email: "emily.moore@example.com",
    address: "010 Walnut St, Suburbia",
    phone: "555-4321",
    gender: "Female",
  },
  {
    name: "Matthew Wright",
    age: 27,
    email: "matthew.wright@example.com",
    address: "111 Spruce St, Outskirts",
    phone: "555-7890",
    gender: "Male",
  },
  {
    name: "Chloe Robinson",
    age: 23,
    email: "chloe.robinson@example.com",
    address: "212 Pine St, Uptown",
    phone: "555-2345",
    gender: "Female",
  },
  {
    name: "Joseph Harris",
    age: 30,
    email: "joseph.harris@example.com",
    address: "313 Cedar St, Downtown",
    phone: "555-8765",
    gender: "Male",
  },
  {
    name: "Lily Martin",
    age: 28,
    email: "lily.martin@example.com",
    address: "414 Birch St, Riverside",
    phone: "555-1234",
    gender: "Female",
  },
];
